### ISSUE TITLE
Traces of merge conflicts in the code

### ISSUE THREAD

**Issue by noahwilliamsson** [terjeio/Trinamic-library#2]
The current master branch has a ton of traces from merge conflicts checked in.

```
% egrep '<<<<<<<|=======|>>>>>>>' * |head -n20
common.c:<<<<<<< HEAD
common.c:=======
common.c:>>>>>>> b687cda0f174c908cc9421b42af9b442f3fa6112
common.h:<<<<<<< HEAD
common.h:=======
common.h:>>>>>>> b687cda0f174c908cc9421b42af9b442f3fa6112
common.h:<<<<<<< HEAD
common.h:=======
common.h:>>>>>>> b687cda0f174c908cc9421b42af9b442f3fa6112
common.h:<<<<<<< HEAD
common.h:=======
common.h:>>>>>>> b687cda0f174c908cc9421b42af9b442f3fa6112
tmc2130.c:<<<<<<< HEAD
tmc2130.c:=======
tmc2130.c:>>>>>>> b687cda0f174c908cc9421b42af9b442f3fa6112
tmc2130.c:<<<<<<< HEAD
tmc2130.c:=======
tmc2130.c:>>>>>>> b687cda0f174c908cc9421b42af9b442f3fa6112
tmc2130.c:<<<<<<< HEAD
tmc2130.c:=======
```

This makes it impossible to compile the code.

``` 
% gcc common.c 
In file included from common.c:39:
./common.h:44:1: error: version control conflict marker in file
<<<<<<< HEAD
^
./common.h:54:1: error: version control conflict marker in file
<<<<<<< HEAD
^
./common.h:139:1: error: version control conflict marker in file
<<<<<<< HEAD
^
common.c:78:1: error: version control conflict marker in file
<<<<<<< HEAD
^
4 errors generated.
```

At least some of them were introduced with commit cdc4fda2.

**Comment by noahwilliamsson** [comment]
Closing as this appears to be resolved with 1f3d07cb.
